version: '3.7'

volumes:
  db-data: {}
  redis-data: {}

services:
  db:
    build:
      context: ./backend
      dockerfile: ./compose/postgres/Dockerfile
    env_file:
     - .envs
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build:
      context: ./backend
      dockerfile: ./compose/django/Dockerfile
    env_file:
     - .envs
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ./compose/django/dev_entrypoint.sh
