# Generated by Django 3.2.4 on 2021-08-17 09:19

from django.db import migrations, models
import django.db.models.deletion
import other_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsOne',
            fields=[
                ('uuid', models.UUIDField(default=other_app.models.get_uuid, primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsTwo',
            fields=[
                ('uuid', models.UUIDField(default=other_app.models.get_uuid, primary_key=True, serialize=False)),
                ('field2', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsHolder',
            fields=[
                ('uuid', models.UUIDField(default=other_app.models.get_uuid, primary_key=True, serialize=False)),
                ('setting_id', models.UUIDField()),
                ('setting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
