# Generated by Django 3.2.4 on 2021-06-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('full_name', models.CharField(max_length=128, verbose_name='Fullname')),
                ('numcode', models.PositiveSmallIntegerField(unique=True, verbose_name='digital code of country')),
                ('alfa3', models.CharField(max_length=3, unique=True, verbose_name='Alfa 3 code')),
                ('alfa2', models.CharField(max_length=2, unique=True, verbose_name='Alfa 2 code')),
                ('sort', models.SmallIntegerField(default=500, verbose_name='Sorting')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Counties',
                'ordering': ('sort', 'alfa3'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='research_app.country')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('shortname', models.CharField(blank=True, max_length=4, null=True, verbose_name='Short name')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='research_app.region')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('name',),
            },
        ),
    ]
